# Generated by Django 5.2.8 on 2025-12-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='from_city',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='stripe_session_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='travel_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='route',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
    ]
